//===----------------------------------------------------------------------===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Main file processed by tablegen to generate the NamedTuple dialect, types and
// operations
//
//===----------------------------------------------------------------------===//

#ifndef NAMED_TUPLE
#define NAMED_TUPLE

include "mlir/Dialect/NamedTuple/IR/NamedTupleDialect.td"
include "mlir/Dialect/NamedTuple/IR/NamedTupleTypes.td"
include "mlir/Dialect/NamedTuple/IR/NamedTupleOps.td"

#endif // NAMED_TUPLE
