//===----------------------------------------------------------------------===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef NAMED_TUPLE_OPS
#define NAMED_TUPLE_OPS

include "mlir/IR/OpAsmInterface.td"

#endif // NAMED_TUPLE_OPS
