name: Commit Access Review

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 1 * *'

permissions:
  contents: read

jobs:
  commit-access-review:
    if: github.repository_owner == 'llvm'
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@v4.2.2
      
      - name: Install dependencies
        run: |
          pip install --require-hashes -r ./llvm/utils/git/requirements.txt
      
      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TASKS_USER_TOKEN }}
        run: |
          python3 .github/workflows/commit-access-review.py $GITHUB_TOKEN

      - name: Upload Triage List
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b #v4.5.0
        with:
          name: triagers
          path: triagers.log
